### ISSUE TITLE
R52 AttributeError

### ISSUE THREAD

**Issue by NSQY** [IFeelBloated/RGSF#1]
OS: Linux kernel 5.8.5

Compiles fine, but it seems that I am unable to call the plugin from the core such as: `core.rgsf.RemoveGrain(clip, ...)`, which outputs `AttributeError: No attribute with the name rgsf exists. Did you mistype a plugin namespace?`

<details>
  <summary>Quick script I used to test this</summary>

import vapoursynth as vs
core = vs.core

src = core.std.BlankClip(width=1920, height=1080, format=vs.YUV444PS, length=240, fpsnum=24000, fpsden=1001, color=[0,0,0])
test = core.rgsf.RemoveGrain(src, mode=4)
test.set_output()

</details>

**Comment by tuilakhanh** [comment]
I got same problem in arch

**Comment by WolframRhodium** [comment]
I compiles it via
```bash
g++ -shared -o librgsf.so *.cpp -O3 -march=native
```
on Linux kernel 5.11.0 and it works as expected. 

May be you should manually load the plugin via `core.std.LoadPlugin` to check the error message?

**Comment by tuilakhanh** [comment]
Thanks, but I already fixed it. I also haven't used linux in a while.
